print("Hello, My name is Azizbek and this is my homework")
adjective = input("Enter an adjective: ")
noun = input("Enter a noun: ")
verb_past_tense = input("Enter a verb (past tense):")
print("\nHere is your story:")
print("The " + adjective + " " + noun + " " + verb_past_tense + " over the lazy dog.")
